### ISSUE TITLE
autoload.php not found

### ISSUE THREAD

**Issue by DavidBruchmann** [kaystrobach/TYPO3.piwikintegration#43]
In the current master I get the following messages shown:

```php
Warning: Uncaught exception 'TYPO3\CMS\Core\Error\Exception' with message 'PHP Warning:
	require_once(/.../typo3conf/piwik/piwik/vendor/autoload.php) [function.require-once]:
		failed to open stream: No such file or directory in typo3conf/ext/piwikintegration/Classes/Lib/Config.php line 86' in typo3/sysext/core/Classes/Error/ErrorHandler.php:101
		Stack trace:
			#0 typo3conf/ext/piwikintegration/Classes/Lib/Config.php(86):
				TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'require_once(/w...', '/kunden/xxxxx_...', 86, Array)
			#1 typo3conf/ext/piwikintegration/Classes/Lib/Config.php(86): tx_piwikintegration_config::initPiwikFrameWork()
			#2 /.../rp-hosting/46 in /kunden/.../rp-hosting/46xx/xxx/.../typo3/sysext/core/Classes/Error/ErrorHandler.php on line 101

Fatal error: tx_piwikintegration_config::initPiwikFrameWork() [function.require]: Failed opening required 'typo3conf/piwik/piwik/vendor/autoload.php' (include_path='.../typo3conf/piwik/piwik/:.../typo3conf/piwik/piwik//libs/:/.../typo3conf/piwik/piwik//plugins/:/.../typo3conf/piwik/piwik//core:/.../typo3conf/piwik/piwik//libs:/.../typo3conf/piwik/piwik//plugins:/.../typo3/contrib/pear/:.:/usr/local/lib/php') in /.../typo3conf/ext/piwikintegration/Classes/Lib/Config.php on line 86
```

Assumption by Kay is that the autoloader was moved:
https://forge.typo3.org/issues/66203

**Comment by DavidBruchmann** [comment]
Having seen the Changelog I remarked that Breaking Changes are not uncommon in piwik.
So it would be helpful to know and download the right version of piwik to download.
Covering all or several versions seems being impossible as changes are more or less unpredictable.

**Comment by DavidBruchmann** [comment]
After verifying the piwik-version on the customers server I remarked that it must have been an old version. The new version has the expected file-paths.
